import Link from "next/link";
import { ArrowRight, BookOpenText, CalendarDays, RotateCcw } from "lucide-react";
import { courses, reviews } from "@/features/student/demo-data";

export default function ReviewsPage() {
  const scheduled = [{ when: "Tomorrow", count: 8 }, { when: "In 3 days", count: 5 }];
  const total = reviews.categories.reduce((sum, category) => sum + category.count, 0);
  return <div className="student-reviews-page pb-12"><header className="student-page-intro"><span className="student-section-path">Your growth</span><h1>Make it stick.</h1><p>Come back to the ideas you want to keep. Review counts and timing here are illustrative.</p></header>
    <div className="student-review-layout"><section className="student-review-feature" aria-labelledby="reviews-today-title"><div className="student-review-feature-copy"><span className="student-review-feature-label"><RotateCcw size={17} aria-hidden="true" /> Review preview</span><h2 id="reviews-today-title">A little recall goes a long way.</h2><p>The full spaced-review session is a later step. You can practise a lesson exercise now.</p><Link href={`/student/learn/${courses[0].id}/${courses[0].lessons[0].id}/exercise`} className="student-primary-button student-button-light">Try an exercise <ArrowRight size={16} aria-hidden="true" /></Link></div><div className="student-review-orbit" role="img" aria-label={`${reviews.due} illustrative items due today`}><span>{reviews.due}</span><small>to revisit</small></div></section><section className="student-review-breakdown" aria-labelledby="review-breakdown-title"><div className="student-insight-heading"><div><h2 id="review-breakdown-title">What&apos;s ready</h2><p>{total} items in this sample plan</p></div><RotateCcw size={19} aria-hidden="true" /></div><div className="student-review-categories">{reviews.categories.map((category, index) => <div key={category.label}><span className={`student-review-dot student-review-dot-${index}`} /><strong>{category.label}</strong><span>{category.count} items</span><div className="student-review-category-track"><span style={{ width: `${category.count / total * 100}%` }} /></div></div>)}</div></section></div>
    <section className="student-review-upcoming" aria-labelledby="upcoming-title"><div className="student-section-title"><div><h2 id="upcoming-title">On the horizon</h2><p>Sample reminders for the next few days</p></div><span>Preview schedule</span></div><div className="student-upcoming-list">{scheduled.map((entry) => <div key={entry.when}><CalendarDays size={19} aria-hidden="true" /><strong>{entry.when}</strong><span>{entry.count} items</span></div>)}</div></section><div className="student-review-next"><BookOpenText size={21} aria-hidden="true" /><p>Want a useful step today? Pick up a lesson and try its short exercise.</p><Link href="/student/learn" className="student-text-link">Go to Learn <ArrowRight size={15} aria-hidden="true" /></Link></div>
  </div>;
}
