"""initial_core_schema

Revision ID: 63f8878d7f72
Revises:
Create Date: 2026-10-01 23:19:44.121435
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "63f8878d7f72"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cefr_levels",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.CheckConstraint("rank > 0", name=op.f("ck_cefr_levels_rank_positive")),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_cefr_levels")),
        sa.UniqueConstraint("rank", name=op.f("uq_cefr_levels_rank")),
    )
    op.create_table(
        "languages",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code <> '' AND code = lower(code)", name=op.f("ck_languages_code_valid")
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_languages")),
    )
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "scope IN ('PLATFORM', 'SCHOOL')", name=op.f("ck_permissions_scope_valid")
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", "scope", name=op.f("uq_permissions_code_scope")),
    )
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.CheckConstraint("scope IN ('PLATFORM', 'SCHOOL')", name=op.f("ck_roles_scope_valid")),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", "scope", name=op.f("uq_roles_code_scope")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("first_name", sa.String(length=150), nullable=True),
        sa.Column("last_name", sa.String(length=150), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email <> '' AND email = btrim(email)", name=op.f("ck_users_email_trimmed")
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'ACTIVE', 'SUSPENDED')", name=op.f("ck_users_status_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_code", sa.String(length=64), nullable=False),
        sa.Column("permission_code", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "scope IN ('PLATFORM', 'SCHOOL')", name=op.f("ck_role_permissions_scope_valid")
        ),
        sa.ForeignKeyConstraint(
            ["permission_code", "scope"],
            ["permissions.code", "permissions.scope"],
            name=op.f("fk_role_permissions_permission_code_scope_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_code", "scope"],
            ["roles.code", "roles.scope"],
            name=op.f("fk_role_permissions_role_code_scope_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_code", "permission_code", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "tenants",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'PERSONAL' AND owner_user_id IS NOT NULL) OR (kind = 'SCHOOL' AND owner_user_id IS NULL)",
            name=op.f("ck_tenants_owner_matches_kind"),
        ),
        sa.CheckConstraint("kind IN ('SCHOOL', 'PERSONAL')", name=op.f("ck_tenants_kind_valid")),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_tenants_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("owner_user_id", name=op.f("uq_tenants_owner_user_id")),
    )
    op.create_table(
        "user_global_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_code", sa.String(length=64), nullable=False),
        sa.Column(
            "role_scope", sa.String(length=16), server_default=sa.text("'PLATFORM'"), nullable=False
        ),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role_scope = 'PLATFORM'", name=op.f("ck_user_global_roles_platform_role_only")
        ),
        sa.ForeignKeyConstraint(
            ["role_code", "role_scope"],
            ["roles.code", "roles.scope"],
            name=op.f("fk_user_global_roles_role_code_role_scope_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_global_roles_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("user_id", "role_code", name=op.f("pk_user_global_roles")),
    )
    op.create_index(
        "ix_user_global_roles_role_user",
        "user_global_roles",
        ["role_code", "user_id"],
        unique=False,
    )
    op.create_table(
        "schools",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug <> '' AND slug = lower(btrim(slug))", name=op.f("ck_schools_slug_normalized")
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'SUSPENDED')", name=op.f("ck_schools_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["tenants.id"], name=op.f("fk_schools_id_tenants"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schools")),
        sa.UniqueConstraint("slug", name=op.f("uq_schools_slug")),
    )
    op.create_table(
        "user_language_profiles",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("language_code", sa.String(length=32), nullable=False),
        sa.Column("initial_cefr_code", sa.String(length=8), nullable=True),
        sa.Column("initial_level_source", sa.String(length=16), nullable=True),
        sa.Column("current_cefr_code", sa.String(length=8), nullable=True),
        sa.Column(
            "school_path_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "communication_path_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "initial_level_source IS NULL OR initial_level_source IN ('SCHOOL', 'PLACEMENT', 'BEGINNER', 'USER')",
            name=op.f("ck_user_language_profiles_initial_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'PAUSED')", name=op.f("ck_user_language_profiles_status_valid")
        ),
        sa.CheckConstraint(
            "(initial_cefr_code IS NULL AND initial_level_source IS NULL) OR (initial_cefr_code IS NOT NULL AND initial_level_source IS NOT NULL)",
            name=op.f("ck_user_language_profiles_initial_level_pair"),
        ),
        sa.ForeignKeyConstraint(
            ["current_cefr_code"],
            ["cefr_levels.code"],
            name=op.f("fk_user_language_profiles_current_cefr_code_cefr_levels"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["initial_cefr_code"],
            ["cefr_levels.code"],
            name=op.f("fk_user_language_profiles_initial_cefr_code_cefr_levels"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["language_code"],
            ["languages.code"],
            name=op.f("fk_user_language_profiles_language_code_languages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_user_language_profiles_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_language_profiles_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_language_profiles")),
        sa.UniqueConstraint(
            "tenant_id",
            "user_id",
            "language_code",
            name=op.f("uq_user_language_profiles_tenant_id_user_id_language_code"),
        ),
    )
    op.create_index(
        "ix_user_language_profiles_user_tenant",
        "user_language_profiles",
        ["user_id", "tenant_id"],
        unique=False,
    )
    op.create_table(
        "classes",
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'ARCHIVED')", name=op.f("ck_classes_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_classes_school_id_schools"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classes")),
        sa.UniqueConstraint("school_id", "id", name=op.f("uq_classes_school_id_id")),
    )
    op.create_index("ix_classes_school_status", "classes", ["school_id", "status"], unique=False)
    op.create_table(
        "school_branding",
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("primary_color", sa.String(length=32), nullable=True),
        sa.Column("secondary_color", sa.String(length=32), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_school_branding_school_id_schools"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("school_id", name=op.f("pk_school_branding")),
    )
    op.create_table(
        "school_languages",
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("language_code", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["language_code"],
            ["languages.code"],
            name=op.f("fk_school_languages_language_code_languages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_school_languages_school_id_schools"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("school_id", "language_code", name=op.f("pk_school_languages")),
    )
    op.create_table(
        "school_memberships",
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('INVITED', 'ACTIVE', 'SUSPENDED', 'LEFT')",
            name=op.f("ck_school_memberships_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_school_memberships_school_id_schools"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_school_memberships_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_school_memberships")),
        sa.UniqueConstraint("school_id", "id", name=op.f("uq_school_memberships_school_id_id")),
        sa.UniqueConstraint(
            "school_id", "user_id", name=op.f("uq_school_memberships_school_id_user_id")
        ),
    )
    op.create_index(
        "ix_school_memberships_user_status",
        "school_memberships",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "class_enrollments",
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("class_id", sa.UUID(), nullable=False),
        sa.Column("student_membership_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "enrolled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'ENDED')", name=op.f("ck_class_enrollments_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "class_id"],
            ["classes.school_id", "classes.id"],
            name=op.f("fk_class_enrollments_school_id_class_id_classes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "student_membership_id"],
            ["school_memberships.school_id", "school_memberships.id"],
            name=op.f("fk_class_enrollments_school_id_student_membership_id_school_memberships"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_class_enrollments")),
        sa.UniqueConstraint(
            "school_id", "class_id", "id", name=op.f("uq_class_enrollments_school_id_class_id_id")
        ),
        sa.UniqueConstraint(
            "school_id",
            "class_id",
            "student_membership_id",
            name=op.f("uq_class_enrollments_school_id_class_id_student_membership_id"),
        ),
    )
    op.create_index(
        "ix_class_enrollments_school_student_status",
        "class_enrollments",
        ["school_id", "student_membership_id", "status"],
        unique=False,
    )
    op.create_table(
        "courses",
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("class_id", sa.UUID(), nullable=True),
        sa.Column("language_code", sa.String(length=32), nullable=False),
        sa.Column("cefr_code", sa.String(length=8), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'GLOBAL' AND school_id IS NULL AND class_id IS NULL) OR (scope = 'SCHOOL' AND school_id IS NOT NULL AND class_id IS NULL) OR (scope = 'CLASS' AND school_id IS NOT NULL AND class_id IS NOT NULL)",
            name=op.f("ck_courses_scope_ownership"),
        ),
        sa.CheckConstraint(
            "scope IN ('GLOBAL', 'SCHOOL', 'CLASS')", name=op.f("ck_courses_scope_valid")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')", name=op.f("ck_courses_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["cefr_code"],
            ["cefr_levels.code"],
            name=op.f("fk_courses_cefr_code_cefr_levels"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_courses_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["language_code"],
            ["languages.code"],
            name=op.f("fk_courses_language_code_languages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "class_id"],
            ["classes.school_id", "classes.id"],
            name=op.f("fk_courses_school_id_class_id_classes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_courses_school_id_schools"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    op.create_index(
        "ix_courses_school_class_status",
        "courses",
        ["school_id", "class_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_courses_school_status_language",
        "courses",
        ["school_id", "status", "language_code"],
        unique=False,
    )
    op.create_index(
        "ix_courses_scope_status_language",
        "courses",
        ["scope", "status", "language_code"],
        unique=False,
    )
    op.create_table(
        "groups",
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("class_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ACTIVE', 'ARCHIVED')", name=op.f("ck_groups_status_valid")),
        sa.ForeignKeyConstraint(
            ["school_id", "class_id"],
            ["classes.school_id", "classes.id"],
            name=op.f("fk_groups_school_id_class_id_classes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
        sa.UniqueConstraint(
            "school_id", "class_id", "id", name=op.f("uq_groups_school_id_class_id_id")
        ),
        sa.UniqueConstraint(
            "school_id", "class_id", "name", name=op.f("uq_groups_school_id_class_id_name")
        ),
    )
    op.create_table(
        "school_membership_permission_grants",
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("membership_id", sa.UUID(), nullable=False),
        sa.Column("permission_code", sa.String(length=128), nullable=False),
        sa.Column(
            "permission_scope",
            sa.String(length=16),
            server_default=sa.text("'SCHOOL'"),
            nullable=False,
        ),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "permission_scope = 'SCHOOL'",
            name=op.f("ck_school_membership_permission_grants_school_permission_only"),
        ),
        sa.ForeignKeyConstraint(
            ["permission_code", "permission_scope"],
            ["permissions.code", "permissions.scope"],
            name=op.f(
                "fk_school_membership_permission_grants_permission_code_permission_scope_permissions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "membership_id"],
            ["school_memberships.school_id", "school_memberships.id"],
            name=op.f(
                "fk_school_membership_permission_grants_school_id_membership_id_school_memberships"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "school_id",
            "membership_id",
            "permission_code",
            name=op.f("pk_school_membership_permission_grants"),
        ),
    )
    op.create_table(
        "school_membership_roles",
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("membership_id", sa.UUID(), nullable=False),
        sa.Column("role_code", sa.String(length=64), nullable=False),
        sa.Column(
            "role_scope", sa.String(length=16), server_default=sa.text("'SCHOOL'"), nullable=False
        ),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role_scope = 'SCHOOL'", name=op.f("ck_school_membership_roles_school_role_only")
        ),
        sa.ForeignKeyConstraint(
            ["role_code", "role_scope"],
            ["roles.code", "roles.scope"],
            name=op.f("fk_school_membership_roles_role_code_role_scope_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "membership_id"],
            ["school_memberships.school_id", "school_memberships.id"],
            name=op.f("fk_school_membership_roles_school_id_membership_id_school_memberships"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "school_id", "membership_id", "role_code", name=op.f("pk_school_membership_roles")
        ),
    )
    op.create_index(
        "ix_school_membership_roles_school_role_member",
        "school_membership_roles",
        ["school_id", "role_code", "membership_id"],
        unique=False,
    )
    op.create_table(
        "teacher_class_assignments",
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("class_id", sa.UUID(), nullable=False),
        sa.Column("teacher_membership_id", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'ENDED')", name=op.f("ck_teacher_class_assignments_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "class_id"],
            ["classes.school_id", "classes.id"],
            name=op.f("fk_teacher_class_assignments_school_id_class_id_classes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "teacher_membership_id"],
            ["school_memberships.school_id", "school_memberships.id"],
            name=op.f(
                "fk_teacher_class_assignments_school_id_teacher_membership_id_school_memberships"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "school_id",
            "class_id",
            "teacher_membership_id",
            name=op.f("pk_teacher_class_assignments"),
        ),
    )
    op.create_index(
        "ix_teacher_class_assignments_school_teacher_status",
        "teacher_class_assignments",
        ["school_id", "teacher_membership_id", "status"],
        unique=False,
    )
    op.create_table(
        "group_enrollments",
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("class_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("class_enrollment_id", sa.UUID(), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "class_id", "class_enrollment_id"],
            ["class_enrollments.school_id", "class_enrollments.class_id", "class_enrollments.id"],
            name=op.f(
                "fk_group_enrollments_school_id_class_id_class_enrollment_id_class_enrollments"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "class_id", "group_id"],
            ["groups.school_id", "groups.class_id", "groups.id"],
            name=op.f("fk_group_enrollments_school_id_class_id_group_id_groups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "school_id",
            "class_id",
            "group_id",
            "class_enrollment_id",
            name=op.f("pk_group_enrollments"),
        ),
    )
    op.create_index(
        "ix_group_enrollments_school_class_enrollment",
        "group_enrollments",
        ["school_id", "class_id", "class_enrollment_id"],
        unique=False,
    )
    op.create_table(
        "lessons",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')", name=op.f("ck_lessons_status_valid")
        ),
        sa.CheckConstraint("position > 0", name=op.f("ck_lessons_position_positive")),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_lessons_course_id_courses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
        sa.UniqueConstraint("course_id", "position", name=op.f("uq_lessons_course_id_position")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lessons")
    op.drop_index("ix_group_enrollments_school_class_enrollment", table_name="group_enrollments")
    op.drop_table("group_enrollments")
    op.drop_index(
        "ix_teacher_class_assignments_school_teacher_status", table_name="teacher_class_assignments"
    )
    op.drop_table("teacher_class_assignments")
    op.drop_index(
        "ix_school_membership_roles_school_role_member", table_name="school_membership_roles"
    )
    op.drop_table("school_membership_roles")
    op.drop_table("school_membership_permission_grants")
    op.drop_table("groups")
    op.drop_index("ix_courses_scope_status_language", table_name="courses")
    op.drop_index("ix_courses_school_status_language", table_name="courses")
    op.drop_index("ix_courses_school_class_status", table_name="courses")
    op.drop_table("courses")
    op.drop_index("ix_class_enrollments_school_student_status", table_name="class_enrollments")
    op.drop_table("class_enrollments")
    op.drop_index("ix_school_memberships_user_status", table_name="school_memberships")
    op.drop_table("school_memberships")
    op.drop_table("school_languages")
    op.drop_table("school_branding")
    op.drop_index("ix_classes_school_status", table_name="classes")
    op.drop_table("classes")
    op.drop_index("ix_user_language_profiles_user_tenant", table_name="user_language_profiles")
    op.drop_table("user_language_profiles")
    op.drop_table("schools")
    op.drop_index("ix_user_global_roles_role_user", table_name="user_global_roles")
    op.drop_table("user_global_roles")
    op.drop_table("tenants")
    op.drop_table("role_permissions")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_table("languages")
    op.drop_table("cefr_levels")
    # ### end Alembic commands ###
