"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, Clock3, TrendingUp } from "lucide-react";
import { courses, languages, weeklyActivity } from "@/features/student/demo-data";
import { useDemoProgress } from "@/features/student/components/DemoProgress";
import { AnimatedCount } from "@/features/student/components/AnimatedCount";
import { ProgressBar } from "@/features/student/components/StudentPrimitives";

export default function ProgressPage() {
  const { getLanguageProgress, results } = useDemoProgress();
  const overall = Math.round(languages.reduce((sum, language) => sum + getLanguageProgress(language.id).percent, 0) / languages.length);
  const sampleMinutes = weeklyActivity.reduce((sum, day) => sum + day.minutes, 0);
  const maxMinutes = Math.max(...weeklyActivity.map((day) => day.minutes), 1);
  const recent = [...results].sort((a, b) => b.completedAt.localeCompare(a.completedAt));

  return <div className="student-progress-page pb-12"><header className="student-page-intro"><span className="student-section-path">Your growth</span><h1>See how far your words can go.</h1><p>Each lesson you finish gives you another way to take part in a conversation.</p></header>
    <section className="student-momentum" aria-labelledby="momentum-title"><div><span className="student-section-path">Learning momentum · demo</span><h2 id="momentum-title">Small steps add up.</h2><p>Progress below combines illustrative starter data with exercises you complete in this browser session.</p><Link href="/student/learn" className="student-primary-button student-button-light">Keep learning <ArrowRight size={16} aria-hidden="true" /></Link></div><div className="student-momentum-score"><span><AnimatedCount value={overall} suffix="%" /></span><small>Average sample progress<br />across your languages</small></div></section>
    <section className="student-section-block" aria-labelledby="language-progress-title"><div className="student-section-title"><div><h2 id="language-progress-title">Your language journeys</h2><p>Follow each language on its own path.</p></div><span>{languages.length} active in this demo</span></div><div className="student-progress-language-grid">{languages.map((language) => { const progress = getLanguageProgress(language.id); const course = courses.find((item) => item.languageId === language.id); return <article key={language.id} className="student-progress-language"><div className="student-progress-language-top"><span className="student-language-monogram" aria-hidden="true">{language.name.slice(0, 2)}</span><span className="student-level">{language.level}</span></div><h3>{language.name}</h3><p>{course?.title}</p><strong className="student-progress-language-value"><AnimatedCount value={progress.percent} suffix="%" /></strong><ProgressBar value={progress.percent} label={`${language.name} illustrative progress`} /><div className="student-progress-language-stats"><span><strong>{progress.completed}/{progress.total}</strong><small>sample lessons</small></span><span><strong>{progress.average}%</strong><small>average score</small></span></div>{course && <Link href={`/student/learn/${course.id}`} className="student-text-link">View course <ArrowRight size={15} aria-hidden="true" /></Link>}</article>; })}</div></section>
    <div className="student-progress-lower"><section className="student-progress-activity" aria-labelledby="weekly-activity-title"><div className="student-insight-heading"><div><h2 id="weekly-activity-title">A week of practice</h2><p>Illustrative activity · {sampleMinutes} minutes total</p></div><TrendingUp size={19} aria-hidden="true" /></div><div className="student-week-chart" role="img" aria-label={weeklyActivity.map((day) => `${day.day}: ${day.minutes} minutes`).join(", ")}>{weeklyActivity.map((day, index) => <div key={day.day} className="student-chart-day" title={`${day.day} — ${day.minutes} min`}><div className="student-chart-track"><div className="student-chart-bar" style={{ height: `${day.minutes / maxMinutes * 100}%`, animationDelay: `${index * 55}ms` }} /></div><span>{day.day}</span><span className="student-chart-tooltip" aria-hidden="true">{day.minutes} min</span></div>)}</div></section><section className="student-progress-recent" aria-labelledby="recent-progress-title"><div className="student-insight-heading"><div><h2 id="recent-progress-title">Your recent steps</h2><p>Exercise results from this browser session</p></div><Clock3 size={19} aria-hidden="true" /></div>{recent.length ? <div className="student-progress-timeline">{recent.map((result) => { const course = courses.find((item) => item.id === result.courseId); const lesson = course?.lessons.find((item) => item.id === result.lessonId); return <div key={result.lessonId}><span><CheckCircle2 size={17} aria-hidden="true" /></span><div><strong>{lesson?.title ?? "Lesson exercise"}</strong><small>Exercise · {Math.round(result.score / result.total * 100)}%</small></div></div>; })}</div> : <div className="student-progress-empty"><p>Complete a short exercise to see your own result here.</p><Link href={`/student/learn/${courses[0].id}/${courses[0].lessons[0].id}/exercise`} className="student-text-link">Try an exercise <ArrowRight size={15} aria-hidden="true" /></Link></div>}</section></div>
  </div>;
}
